### ISSUE TITLE
Adminshop funktioniert nicht :)

### ISSUE THREAD

**Issue by LucarioMi** [Neotras/Copeworld#3]
Der Adminshop für 64 Gold funktioniert nicht.
Auf dem Schild steht anstatt B57600 nur 57600.
Aufgrund dessen funktioniert es wahrscheinlich nicht.
Wär toll wenn du dich drum kümmern könntest.
Danke

Luca

**Comment by Neotras** [comment]
Behoben

**Comment by Neotras** [comment]
Behoben
